### ISSUE TITLE
domain_join_info with empty block crashes terraform

### ISSUE THREAD

**Issue by liberops** [arnvid/terraform-provider-appstream#11]
Hi,
Is there a way to have an empty arguments for the **domain_join_info** block in the fleet creation without crashing Terraform?
I would like to be able to put something like "" or null.

_panic: interface conversion: interface {} is nil, not map[string]interface {}_

Thanks

**Comment by arnvid** [comment]
Hi - have not seen this. I will try to reproduce

**Comment by arnvid** [comment]
While the domain_join_info comes from the official terraform provider - the custom provider have domain_info - but as the functionality is now in the official terraform provider - I am going to archive this one.
