### ISSUE TITLE
'Provider produced inconsistent result after apply' when applying appstream_stack_attachment

### ISSUE THREAD

**Issue by JCBlouin** [arnvid/terraform-provider-appstream#12]
When Terraform creates the fleet/stack attachment, I see the following error:
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to appstream_stack_attachment.attachment, provider
│ "provider[\"registry.terraform.io/arnvid/appstream\"]" produced an unexpected new value: Root resource was present, but
│ now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

Perhaps this is because I'm using the hashicorp/aws provider to create the fleet and stack?

Here are the relevant resources:
`
#############
\### STACK ###
#############

resource "aws_appstream_stack" "stack" {
  name         = "${local.region}_stack"
  description  = "${local.region} AppStream Stack"
  display_name = local.fleetdisplayname
  \# feedback_url = "http://your-domain/feedback"
  \# redirect_url = "http://your-domain/redirect"

  user_settings {
    action     = "CLIPBOARD_COPY_FROM_LOCAL_DEVICE"
    permission = "ENABLED"
  }
  user_settings {
    action     = "CLIPBOARD_COPY_TO_LOCAL_DEVICE"
    permission = "ENABLED"
  }
  user_settings {
    action     = "FILE_UPLOAD"
    permission = "ENABLED"
  }
  user_settings {
    action     = "FILE_DOWNLOAD"
    permission = "ENABLED"
  }
  user_settings {
    action     = "PRINTING_TO_LOCAL_DEVICE"
    permission = "ENABLED"
  }
  user_settings {
    action     = "DOMAIN_PASSWORD_SIGNIN"
    permission = "ENABLED"
  }
  \#   user_settings {
  \#   action     = "DOMAIN_SMART_CARD_SIGNIN"
  \#   permission = "DISABLED"
  \# }

  application_settings {
    enabled = false
    # settings_group = "SettingsGroup"
  }

  tags = {
    Application = local.apptag
  }
}

#############
\### FLEET ###
#############

resource "aws_appstream_fleet" "fleet" {
  name = local.fleetname

  compute_capacity {
    desired_instances = 1
  }

  description                        = local.fleetdisplayname
  idle_disconnect_timeout_in_seconds = 300
  display_name                       = local.fleetdisplayname
  enable_default_internet_access     = false
  fleet_type                         = local.fleet_type
  image_name                         = local.image_name
  instance_type                      = local.instance_type

  max_user_duration_in_seconds = local.max_user_duration_in_seconds

  vpc_config {
    subnet_ids = [aws_subnet.appstream_private_a.id, aws_subnet.appstream_private_b.id]
  }

  tags = {
    Application = local.apptag
  }
  
}

resource "appstream_stack_attachment" "attachment" {
  appstream_stack_id = aws_appstream_stack.stack.id
  appstream_fleet_id = aws_appstream_fleet.fleet.id

  depends_on = [aws_appstream_stack.stack,aws_appstream_fleet.fleet]
}
`

This also seems to cause problems when destroying:
╷
│ Error: error deleting Appstream Fleet (Signals_Fleet): ResourceInUseException: The fleet Signals_Fleet is associated with a stack. To delete the fleet, you must dissociate it from the stack.
│
│
╵
╷
│ Error: error deleting Appstream Stack (us-west-2_stack): ResourceInUseException: Cannot delete stack us-west-2_stack. This stack has fleets associated with it. Only stacks with no fleets associated with it can be deleted.
│
│
╵

**Comment by arnvid** [comment]
Afaik - appstream_ provider is not compatible with appstream of the aws provider.
