### ISSUE TITLE
Compatibility with Terraform 1.0.0

### ISSUE THREAD

**Issue by Riice** [arnvid/terraform-provider-appstream#6]
Would it be possible to rebuild and enable the provider to work with Terraform 1.0.0 ?
Currently, running an init results in the following:
`│ Error: Incompatible provider version
│ Provider registry.terraform.io/arnvid/appstream v1.0.8 does not have a package available for your current platform, linux_386.
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.`

**Comment by arnvid** [comment]
Hi 
I have previously used the provider with Terraform 0.13 and 0.12. And lately we have started using TF0.14 but I will see what is needed for TF1.0.0..

**Comment by arnvid** [comment]
Tested latest build locally with 0.14, 0.15 and 1.0.0.
Will be released today.

**Comment by Riice** [comment]
Thanks very much!
