### ISSUE TITLE
Issue with Tags modification

### ISSUE THREAD

**Issue by ankushpadmawar** [arnvid/terraform-provider-appstream#7]
I am using terraform version 0.12.24

I am not able to add/remove/modify tags once fleet is created.
Terraform detects the changes and it gets pushed to tfstate file, but those changes does not gets applied on AWS side.

Can you please help me with this issue.

**Comment by ankushpadmawar** [comment]
Same issue with the Security Group and Subnets modification

**Comment by arnvid** [comment]
Hi 
I have been working on some changes for a while and will look at the tags and see that they are added properly

**Comment by arnvid** [comment]
Tags are resolved in next release

**Comment by ankushpadmawar** [comment]
Thank you @arnvid :)

Also, are you planning on adding modifications in subnets and security groups?

**Comment by arnvid** [comment]
@ankushpadmawar - bot of these require recreation of the fleet. I have a working build for it, but are testing some final parts now.

**Comment by arnvid** [comment]
Appstream is now supported by the official terraform provider since 3.61.0 (October 01, 2021)
